[package]
name = "bud_brawl"
version = "0.1.0"
edition = "2021"

[dependencies]
dyn-clone = "1.0.20"
libnoise = "1.2.0"
rand = "0.9.2"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["image", "gfx", "mixer"]
